vich_uploader:
  db_driver: orm

  mappings:
      skill_logo:
         uri_prefix: /images/skill
         upload_destination: '%upload_directory%'
      cover_image:
        uri_prefix: /images/skill
        upload_destination: '%upload_directory%'